services:
  gymnetic-sql:
    image: mysql:8.0
    container_name: gymnetic-sql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  gymnetic-backend:
    image: supplement-image
    container_name: gymnetic-backend
    ports:
      - "8080:8080"
    depends_on:
      - gymnetic-sql
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql-data:
